/**
 * AI Publishing Engine — Types
 *
 * 9-phase editorial pipeline with AI integration.
 * Maps to existing editorial_stages + editorial_jobs tables.
 */

// ─── Phase Keys ──────────────────────────────────────────────────────

export type PublishingPhaseKey =
  | "manuscript_intake"
  | "ai_analysis"
  | "orthotypographic_correction"
  | "style_editing"
  | "auto_layout"
  | "interior_design"
  | "cover_design"
  | "final_review"
  | "final_export";

// ─── Phase Status ────────────────────────────────────────────────────

export type PhaseStatus = "pending" | "processing" | "completed" | "failed" | "needs_review";

// ─── AI Provider ─────────────────────────────────────────────────────

export type AiProvider = "openai" | "claude" | "grammarly" | "midjourney" | "atticus" | "internal";

// ─── Phase Definition ────────────────────────────────────────────────

export interface PublishingPhaseDefinition {
  key: PublishingPhaseKey;
  order: number;
  label: string;
  shortLabel: string;
  description: string;
  aiProvider: AiProvider;
  aiProviderLabel: string;
  /** Maps to existing editorial_stages.stage_key for DB compatibility */
  legacyStageKey: string;
  /** AI task key for the job queue */
  aiTaskKey: string | null;
  /** Whether this phase requires human review before continuing */
  requiresHumanReview: boolean;
  /** Whether AI can auto-process this phase */
  isAiAutomated: boolean;
  /** Downloadable outputs generated by this phase */
  outputs: PhaseOutput[];
  /** Summary message template shown when phase completes */
  completionMessageTemplate: string;
}

// ─── Phase Output ────────────────────────────────────────────────────

export interface PhaseOutput {
  key: string;
  label: string;
  fileType: "docx" | "pdf" | "epub" | "kindle" | "png" | "txt";
  description: string;
}

// ─── Pipeline Run ────────────────────────────────────────────────────

export interface PipelineRun {
  id: string;
  projectId: string;
  status: "idle" | "running" | "completed" | "failed" | "paused";
  currentPhaseKey: PublishingPhaseKey | null;
  currentPhaseIndex: number;
  totalPhases: number;
  completedPhases: number;
  startedAt: string | null;
  completedAt: string | null;
  error: string | null;
}

// ─── Phase Result ────────────────────────────────────────────────────

export interface PhaseResult {
  phaseKey: PublishingPhaseKey;
  status: PhaseStatus;
  summary: string;
  score: number | null;
  findings: PhaseFinding[];
  outputFiles: PhaseOutputFile[];
  aiProvider: AiProvider;
  processingTimeMs: number;
  startedAt: string;
  completedAt: string | null;
}

export interface PhaseFinding {
  type: "error" | "warning" | "suggestion" | "info";
  description: string;
  location: string | null;
  correction: string | null;
  confidence: number | null;
}

export interface PhaseOutputFile {
  key: string;
  label: string;
  fileType: string;
  storagePath: string;
  version: number;
  generatedBy: "ai" | "human";
  createdAt: string;
}

// ─── Prompt Edit ─────────────────────────────────────────────────────

export interface PhasePromptEdit {
  id: string;
  projectId: string;
  phaseKey: PublishingPhaseKey;
  prompt: string;
  createdAt: string;
  createdBy: string | null;
}

// ─── Amazon Format Config ────────────────────────────────────────────

export interface AmazonFormatConfig {
  trimSize: "5x8" | "5.5x8.5" | "6x9" | "7x10" | "8.5x11";
  bookType: "paperback" | "hardcover" | "ebook";
  paperType: "cream" | "white";
  bleed: boolean;
}

// ─── 12-Day Author Timeline ─────────────────────────────────────────

export interface AuthorTimelineDay {
  day: number;
  dayRange: string;
  label: string;
  labelEn: string;
  description: string;
  descriptionEn: string;
  status: "completed" | "in_progress" | "upcoming" | "pending";
  phaseKeys: PublishingPhaseKey[];
}
